export class EventTypes {
    static  CLOSE_PROCESS_INSTANCE = "CLOSE_PROCESS_INSTANCE"
    static CREATE_PROCESS_INSTANCE = "CREATE_PROCESS_INSTANCE"
    static CREATE_FLOW_EVENT = "CREATE_FLOW_EVENT"
    static CLOSE_FLOW_EVENT = "CLOSE_FLOW_EVENT"
    static FAIL_FLOW_EVENT = "FAIL_FLOW_EVENT"
    static ABORT_FLOW_EVENT = "ABORT_FLOW_EVENT"
}