export class EventTypes {
    static  CLOSE_PROCESS_INSTANCE = "CLOSE_PROCESS_INSTANCE"
    static CREATE_PROCESS_INSTANCE = "CREATE_PROCESS_INSTANCE"
    static CREATE_FLOW_EVENT = "CREATE_FLOW_EVENT"
}